// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYzq7vt-f1xopKm6bmTi3OAevh3r46YeA',
    appId: '1:146504622189:web:018ebc1617c8818f92df64',
    messagingSenderId: '146504622189',
    projectId: 'delivery-23b4c',
    authDomain: 'delivery-23b4c.firebaseapp.com',
    storageBucket: 'delivery-23b4c.appspot.com',
    measurementId: 'G-09HWT7VZ37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIAhSiOMEGyi7ZrIKOxgIhFYrvnu3qXHc',
    appId: '1:146504622189:android:f6d49f860ea768c292df64',
    messagingSenderId: '146504622189',
    projectId: 'delivery-23b4c',
    storageBucket: 'delivery-23b4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6uni93wzHQDZqyDTS6cx0MoTbevDA8S0',
    appId: '1:146504622189:ios:8bde93d50c34915f92df64',
    messagingSenderId: '146504622189',
    projectId: 'delivery-23b4c',
    storageBucket: 'delivery-23b4c.appspot.com',
    iosBundleId: 'com.example.delivaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6uni93wzHQDZqyDTS6cx0MoTbevDA8S0',
    appId: '1:146504622189:ios:8bde93d50c34915f92df64',
    messagingSenderId: '146504622189',
    projectId: 'delivery-23b4c',
    storageBucket: 'delivery-23b4c.appspot.com',
    iosBundleId: 'com.example.delivaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYzq7vt-f1xopKm6bmTi3OAevh3r46YeA',
    appId: '1:146504622189:web:249fa6560bfd086792df64',
    messagingSenderId: '146504622189',
    projectId: 'delivery-23b4c',
    authDomain: 'delivery-23b4c.firebaseapp.com',
    storageBucket: 'delivery-23b4c.appspot.com',
    measurementId: 'G-M8C2RH09TR',
  );
}

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);